### ISSUE TITLE
random_walk_deep_net.ipynb

### ISSUE THREAD

**Issue by waudinio27** [twiecki/WhileMyMCMCGentlySamples#12]
Hallo Thomas,

Ist es möglich vom -  random_walk_deep_net.ipynb eine Version mit Finanzdaten von yfinance zu machen? Zum Beispiel vom SPY 500 oder dem DAX 40?

Das Projekt ist hochinteressant und sehr innovativ, aber ich selber schaffe es wohl kaum das Notebook entsprechend anzupassen.  Ich habe schon länger nach einer Art und Weise gesucht, die nicht explizit verlangt das man ein estimation window oder Schätzfenster festlegt und sich damit an die aktuelle Marktsituation anpassen kann. Eigentlich hatte ich die Hoffnung darauf schon fast aufgegeben.

Das MAP nicht sehr gut funktioniert macht für mich übrigens intuitiv sehr viel Sinn. 

Am allerbesten wäre es falls auch gezeigt werden könnte wie man dann nach dem Training  auch die aktuellen Vorhersagen treffen kann.

Falls du https://www.buymeacoffee.com/ zu deiner Seite hinzufügst dann kann ich dir damit einen Kaffee spendieren. 

Vielen Lieben Dank und Grüße

**Comment by twiecki** [comment]
Hi, shouldn't be that difficult, just load in different data. If you have questions about pymc3 you can post them on https://discourse.pymc.io
