### ISSUE TITLE
`zip` should be `izip` in bayesian_neural_network.ipynb 

### ISSUE THREAD

**Issue by alxempirical** [twiecki/WhileMyMCMCGentlySamples#3]
Maybe these are python 2 vs python 3 differences.  I am running 2.

This code blows up because it's trying to generate an infinite list.

``` python
minibatches = zip(
    Xminibatch, 
    Yminibatch,
)
```

**Comment by twiecki** [comment]
Should be fixed with https://github.com/twiecki/WhileMyMCMCGentlySamples/commit/a567c9eeb47c7306bdce969a3e2265ff02ee2569.
