### ISSUE TITLE
array reshape

### ISSUE THREAD

**Issue by switchscorbra** [twiecki/WhileMyMCMCGentlySamples#7]
the below line of code provides the following error

contour = ax.contourf(X1_grid, X2_grid, out_sample.eval().mean(axis=0).reshape(100, 100), cmap=cmap)

ValueError: cannot reshape array of size 100 into shape (100,100)
i am not sure what the issue is

**Comment by twiecki** [comment]
I'll look into it, which post is that?

**Comment by switchscorbra** [comment]
This one:

http://twiecki.github.io/blog/2016/06/01/bayesian-deep-learning/

Also, any help with how I can apply this to UCI data will be much appreciated.

**Comment by twiecki** [comment]
@switchscorbra I updated the blog post, see if that fixes it.

**Comment by switchscorbra** [comment]
Thank you
